[general]
rxdelay = 500
txdelay = 500
rxtone = 523
txtone = 740
thread_sleep = 0.01
gpio_buzzer_tx = 27
gpio_buzzer_rx = 22
gpio_dit = 26
gpio_dah = 16
gpio_straight = 20
glitch_filter_dit = 5000
glitch_filter_dah = 5000
glitch_filter_straight = 5000
reverse_paddles = 0
keyer_mode = a
straight_disable_ms = 1000
wpm = 20
url = wss://vail.woozle.org/chat
repeater = General
