[general]
rxdelay = 500
txdelay = 500
rxtone = 523
thread_sleep = 0.01
gpio_buzzer = 27
gpio_dit = 26
gpio_dah = 16
glitch_filter_dit = 5000
glitch_filter_dah = 5000
url = wss://vail.woozle.org/chat
repeater = General
